permalink: /blog/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "node_modules"]
highlighter: rouge
markdown: kramdown

external: http://octoprint.org
#external: http://192.168.1.3:4000
baseurl: ""

title : OctoPrint.org
tagline: The snappy web interface for your 3D printer.
description: OctoPrint is the snappy web interface for your 3D printer that allows you to control and monitor all aspects of your printer and print jobs, right from your browser.

paginate: 10
paginate_path: "/blog/page:num/"

permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!-- more -->

author:
  name: Gina Häußge
  twitter: foosel

patreon: https://patreon.com/foosel
paypal: https://paypal.me/foosel
sourcerepo: https://github.com/foosel/OctoPrint

twitter: OctoPrint3D
facebook: OctoPrint
gplus: OctoPrintOrg

twitterlink: https://twitter.com/OctoPrint3D
facebooklink: https://facebook.com/OctoPrint
gpluslink: https://plus.google.com/+OctoprintOrg/posts

gems: [jekyll-paginate]