name: "Nightly merge"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ðŸ”€ Merge master into maintenance
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          stable_branch: "master"
          development_branch: "maintenance"
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ”€ Merge staging/bugfix into maintenance
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          stable_branch: "staging/bugfix"
          development_branch: "maintenance"
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ”€ Merge staging/maintenance into maintenance
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          stable_branch: "staging/bugfix"
          development_branch: "maintenance"
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ”€ Merge maintenance into devel
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          stable_branch: "maintenance"
          development_branch: "devel"
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
