name: Test install on Python 2

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [test_install_py2]
  schedule:
    - cron: '0 */12 * * *'

jobs:
  install-master:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: â¬‡ Checkout code
        uses: actions/checkout@v2
      - name: ğŸ‘· Build and install checkout
        run: |
          pip install .
    - name: ğŸ“§ Discord success notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook_foosel }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'â˜‘ï¸ Test install on Python 2 for `master` was successful'
    - name: ğŸ“§ Discord failure notification
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook_foosel }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'ğŸš« Test install on Python 2 for `master` failed'

  install-latest:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: ğŸ‘· Build and install latest from PyPI
        run: |
          pip install OctoPrint
    - name: ğŸ“§ Discord success notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook_foosel }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'â˜‘ï¸ Test install on Python 2 for latest release was successful'
    - name: ğŸ“§ Discord failure notification
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.discord_webhook_foosel }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'ğŸš« Test install on Python 2 for latest release failed'
