name: Trigger doc build
on:
  push:
    branches:
      - master
      - maintenance
      - devel
  release:
    types:
      - released
      - prereleased

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: github.repository == 'OctoPrint/OctoPrint'
    steps:
      - name: ðŸš€ Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPODISPATCH_TOKEN }}
          repository: OctoPrint/docs.octoprint.org
          event-type: docs
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
